# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='student_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
