# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171228_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
