# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_taskdata_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdata',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
    ]
