# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='overview',
            field=models.FileField(null=True, upload_to=tasks.models.task_file_directory_path),
        ),
    ]
