# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20171220_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data_zip',
            field=models.FileField(null=True, upload_to=tasks.models.task_file_directory_path),
        ),
        migrations.AddField(
            model_name='task',
            name='rules',
            field=models.FileField(null=True, upload_to=tasks.models.task_file_directory_path),
        ),
    ]
