# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_paper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paper',
            new_name='Report',
        ),
    ]
