# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20180116_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='paper',
            new_name='report',
        ),
    ]
